---
- name: Install development tools.
  package:
    state: latest
    name:
      - ack-grep
      - byobu
      - dnsutils
      - dstat
      - fish
      - jq
      - mailutils
      - net-tools
      - screen
      - sqlite3
      - tcpdump
      - tmux
      - tree
      - vim
      - zip
      - zsh
- import_tasks: ctags.yml
- import_role:
    name: "geerlingguy.docker"
