---
- name: Create /etc/environment
  template:
    src: templates/environment.j2
    dest: /etc/environment
    mode: 0644
  when:
    - AWS_ACCESS_KEY_ID is defined
    - AWS_ACCESS_KEY_ID != ""
    - AWS_SECRET_ACCESS_KEY is defined
    - AWS_SECRET_ACCESS_KEY != ""
