---
- import_role:
    name: "lean_delivery.java"
- name: install maven (and other packages if needed)
  become: yes
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - maven

